compile:
  platforms:
    - uno
    - due
    - zero
    - leonardo
    - m4
#    - esp32  See issue: https://github.com/WesWedding/TweenDuino/issues/32
    - esp8266
    - mega2560
    - nano_every
  libraries:
    - Adafruit NeoPixel
  
